import { useState } from 'react';
import { Bell, Check, ChevronRight, MapPin, MessageCircle, Search, SlidersHorizontal, Users, X } from 'lucide-react';
import { MOCK_PROFILE, MOCK_USER_SKILLS, SKILLS } from './supabaseClient';
import type { LocalProfile } from './types';
import { useLocalProfiles } from './useLocalProfiles';

const matches: LocalProfile[] = [
  { id: 'P-20260915-002', auth_id: null, full_name: 'Maya Chen', email: 'maya@example.com', bio: 'Ceramicist learning the art of natural sourdough.', zip_code: '10011', created_at: '2026-09-10', distance_miles: 1.2, match_score: 96, user_skills: [{ id: 'US-20260915-003', profile_id: 'P-20260915-002', skill_id: 1, skill_type: 'teach', experience_level: 'advanced', skill: SKILLS[0] }, { id: 'US-20260915-004', profile_id: 'P-20260915-002', skill_id: 3, skill_type: 'learn', experience_level: 'beginner', skill: SKILLS[2] }] },
  { id: 'P-20260915-003', auth_id: null, full_name: 'Noah Williams', email: 'noah@example.com', bio: 'Street photographer and lifelong guitar tinkerer.', zip_code: '10014', created_at: '2026-09-08', distance_miles: 2.4, match_score: 89, user_skills: [{ id: 'US-20260915-005', profile_id: 'P-20260915-003', skill_id: 2, skill_type: 'teach', experience_level: 'advanced', skill: SKILLS[1] }, { id: 'US-20260915-006', profile_id: 'P-20260915-003', skill_id: 4, skill_type: 'learn', experience_level: 'intermediate', skill: SKILLS[3] }] },
];
const nearby: LocalProfile[] = [
  { id: 'P-20260915-004', auth_id: null, full_name: 'Priya Shah', email: 'priya@example.com', bio: 'Plant parent, watercolor beginner, and curious maker.', zip_code: '10003', created_at: '2026-09-03', distance_miles: 3.1, user_skills: [{ id: 'US-20260915-007', profile_id: 'P-20260915-004', skill_id: 7, skill_type: 'teach', experience_level: 'intermediate', skill: SKILLS[6] }, { id: 'US-20260915-008', profile_id: 'P-20260915-004', skill_id: 5, skill_type: 'learn', experience_level: 'beginner', skill: SKILLS[4] }] },
];

export function Dashboard() {
  const [toast, setToast] = useState('');
  const [requested, setRequested] = useState<string[]>([]);
  const localProfiles = useLocalProfiles(MOCK_PROFILE.zip_code);
  const displayedProfiles = localProfiles.data.length > 0 ? localProfiles.data : [...matches, ...nearby];
  const displayedMatches = displayedProfiles.slice(0, 2);
  const displayedNearby = displayedProfiles.slice(2);
  function requestSwap(profile: LocalProfile) { setRequested([...requested, profile.id]); setToast(`Swap request sent to ${profile.full_name}`); window.setTimeout(() => setToast(''), 3000); }
  return <main className="min-h-screen bg-[#080b10]"><nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6"><div className="flex items-center gap-2 text-sm font-semibold tracking-wide text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-300 shadow-[0_0_14px_#6ee7b7]" />LOCAL / HOBBYIST</div><div className="flex items-center gap-3"><button className="rounded-full border border-white/10 p-2 text-slate-400 hover:text-white"><Bell size={18} /></button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-emerald-300 to-violet-400 text-sm font-bold text-slate-950">AM</div></div></nav>
    <div className="mx-auto grid max-w-7xl gap-6 px-5 pb-12 lg:grid-cols-[280px_1fr]"><aside className="glass h-fit rounded-3xl p-5 lg:sticky lg:top-5"><div className="mb-7 flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-300 to-cyan-400 text-lg font-bold text-slate-950">AM</div><div><div className="font-medium">{MOCK_PROFILE.full_name}</div><div className="flex items-center gap-1 text-xs text-slate-500"><MapPin size={12} /> {MOCK_PROFILE.zip_code} · New York</div></div></div><div className="mb-7 rounded-2xl bg-black/20 p-4"><div className="mb-3 text-xs uppercase tracking-wider text-slate-500">Your swap profile</div><p className="text-sm leading-6 text-slate-400">{MOCK_PROFILE.bio}</p></div><div className="mb-7 grid grid-cols-2 gap-2">{[['12', 'Profile views'], ['4', 'Active swaps']].map(([value, label]) => <div key={label} className="rounded-xl border border-white/[0.07] p-3"><div className="text-xl font-semibold">{value}</div><div className="mt-1 text-[10px] text-slate-500">{label}</div></div>)}</div><div className="space-y-3"><div className="flex items-center justify-between text-xs text-slate-500"><span>Teaching</span><span className="text-emerald-300">{MOCK_USER_SKILLS.filter((item) => item.skill_type === 'teach').length}</span></div><div className="flex flex-wrap gap-2">{MOCK_USER_SKILLS.filter((item) => item.skill_type === 'teach').map((item) => <span key={item.id} className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-2.5 py-1 text-xs text-emerald-200">{item.skill?.name}</span>)}</div><div className="flex items-center justify-between pt-2 text-xs text-slate-500"><span>Learning</span><span className="text-violet-300">{MOCK_USER_SKILLS.filter((item) => item.skill_type === 'learn').length}</span></div><div className="flex flex-wrap gap-2">{MOCK_USER_SKILLS.filter((item) => item.skill_type === 'learn').map((item) => <span key={item.id} className="rounded-full border border-violet-400/30 bg-violet-400/10 px-2.5 py-1 text-xs text-violet-200">{item.skill?.name}</span>)}</div></div><button className="mt-8 w-full rounded-xl border border-white/10 py-3 text-sm text-slate-300 transition hover:bg-white/5">Edit profile</button></aside>
      <section><header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-2 text-sm text-emerald-300">Tuesday, September 15</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Your local circle</h1><p className="mt-2 text-slate-500">People nearby who make learning feel natural.</p></div><div className="flex gap-2"><button className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2.5 text-sm text-slate-400"><SlidersHorizontal size={16} /> Filters</button><button className="rounded-xl border border-white/10 p-2.5 text-slate-400"><Search size={17} /></button></div></header>{localProfiles.loading && <div className="mb-5 text-xs text-slate-500">Loading live local profiles...</div>}{localProfiles.error && <div className="mb-5 text-xs text-amber-300">Showing prototype matches while live profiles are unavailable.</div>}<section className="mb-9"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-300" /><h2 className="font-medium">Perfect mutual matches</h2><span className="rounded-full bg-emerald-300/10 px-2 py-0.5 text-xs text-emerald-300">{displayedMatches.length}</span></div><button className="flex items-center gap-1 text-xs text-slate-500 hover:text-white">View all <ChevronRight size={14} /></button></div><div className="grid gap-4 xl:grid-cols-2">{displayedMatches.map((person) => <PersonCard key={person.id} person={person} onRequest={requestSwap} requested={requested.includes(person.id)} mutual />)}</div></section><section><div className="mb-4 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-violet-300" /><h2 className="font-medium">Nearby explorers</h2><span className="rounded-full bg-violet-300/10 px-2 py-0.5 text-xs text-violet-300">{displayedNearby.length}</span></div><div className="grid gap-4 xl:grid-cols-2">{displayedNearby.map((person) => <PersonCard key={person.id} person={person} onRequest={requestSwap} requested={requested.includes(person.id)} />)}</div></section></section></div>{toast && <div className="fixed bottom-6 right-6 flex items-center gap-3 rounded-xl border border-emerald-300/20 bg-[#10221d] px-4 py-3 text-sm text-emerald-100 shadow-2xl"><Check size={17} className="text-emerald-300" />{toast}</div>}</main>;
}

function PersonCard({ person, onRequest, requested, mutual = false }: { person: LocalProfile; onRequest: (person: LocalProfile) => void; requested: boolean; mutual?: boolean }) {
  const teaches = person.user_skills.filter((item) => item.skill_type === 'teach');
  const learns = person.user_skills.filter((item) => item.skill_type === 'learn');
  return <article className="glass rounded-2xl p-5 transition hover:border-white/20"><div className="flex items-start justify-between"><div className="flex gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-violet-300 to-fuchsia-400 font-semibold text-slate-950">{person.full_name.split(' ').map((name) => name[0]).join('')}</div><div><h3 className="font-medium">{person.full_name}</h3><div className="mt-1 flex items-center gap-2 text-xs text-slate-500"><MapPin size={12} /> {person.distance_miles} miles away {mutual && <span className="text-emerald-300">· {person.match_score}% match</span>}</div></div></div><button className="text-slate-600 hover:text-white"><MessageCircle size={17} /></button></div><p className="my-4 line-clamp-2 text-sm leading-6 text-slate-400">{person.bio}</p><div className="grid grid-cols-2 gap-3 border-t border-white/[0.07] pt-4"><div><div className="mb-2 text-[10px] uppercase tracking-wider text-slate-600">Can teach</div>{teaches.map((item) => <span key={item.id} className="mr-1 inline-block rounded-full border border-emerald-400/25 bg-emerald-400/[0.08] px-2 py-1 text-xs text-emerald-200">{item.skill?.name}</span>)}</div><div><div className="mb-2 text-[10px] uppercase tracking-wider text-slate-600">Wants to learn</div>{learns.map((item) => <span key={item.id} className="mr-1 inline-block rounded-full border border-violet-400/25 bg-violet-400/[0.08] px-2 py-1 text-xs text-violet-200">{item.skill?.name}</span>)}</div></div><button onClick={() => onRequest(person)} disabled={requested} className={`mt-5 flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-medium transition ${requested ? 'bg-emerald-300/10 text-emerald-300' : 'bg-white/[0.07] text-slate-200 hover:bg-emerald-300 hover:text-emerald-950'}`}>{requested ? <><Check size={15} /> Request sent</> : <>Propose a swap <ChevronRight size={15} /></>}</button></article>;
}
