import { FormEvent, useEffect, useRef, useState } from "react";
import type { Product, Order, CartItem } from "./types";

const peso = (value: number) => `₱${Number(value || 0).toFixed(2)}`;
const api = async <T,>(path: string, options?: RequestInit): Promise<T> => {
  const response = await fetch(path, { credentials: "include", headers: { "Content-Type": "application/json" }, ...options });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Request failed");
  return result;
};

export function POS({ products, orders, onSaved, setNotice }: { products: Product[]; orders: Order[]; onSaved: () => Promise<void>; setNotice: (message: string) => void }) {
  const [cart, setCart] = useState<Record<string, CartItem>>({});
  const [barcode, setBarcode] = useState("");
  const [customer, setCustomer] = useState("Walk-in customer");
  const [receipt, setReceipt] = useState<{ order: Order; items: CartItem[] } | null>(null);
  const barcodeRef = useRef<HTMLInputElement>(null);
  const subtotal = Object.values(cart).reduce((sum, item) => sum + Number(item.base_price) * item.quantity, 0);
  const tax = Object.values(cart).reduce((sum, item) => sum + Number(item.base_price) * Number(item.tax_rate || 0) * item.quantity, 0);
  const add = (product: Product) => setCart((current) => ({ ...current, [product.product_id]: { ...product, quantity: (current[product.product_id]?.quantity || 0) + 1 } }));
  const scan = async (event: FormEvent) => { event.preventDefault(); if (!barcode.trim()) return; try { const product = await api<Product>(`/api/products/barcode/${encodeURIComponent(barcode.trim())}`); add(product); setBarcode(""); setNotice(`${product.product_name} added to order.`); } catch (error) { setNotice((error as Error).message); } };
  const checkout = async () => { try { const receiptItems = Object.values(cart); const result = await api<{ order: Order }>("/api/checkout", { method: "POST", body: JSON.stringify({ customer_name: customer, items: receiptItems.map((item) => ({ product_id: item.product_id, quantity: item.quantity })), payment_method: "cash" }) }); setReceipt({ order: result.order, items: receiptItems }); setCart({}); await onSaved(); setNotice(`Order #${result.order.order_number} completed.`); } catch (error) { setNotice((error as Error).message); } };
  useEffect(() => { barcodeRef.current?.focus(); }, []);
  return <section className="content pos-screen"><div className="pos-main"><div className="panel scan-panel"><form onSubmit={scan}><label>Barcode scanner<input ref={barcodeRef} autoComplete="off" placeholder="Scan or type barcode, then press Enter" value={barcode} onChange={(event) => setBarcode(event.target.value)} /></label><button className="save-product" type="submit">Add barcode</button></form></div><div className="pos-products">{products.filter((product) => product.is_active).map((product) => <button className="pos-product" key={product.product_id} onClick={() => add(product)}><span>☕</span><b>{product.product_name}</b><small>{product.sku} · {peso(product.base_price)}</small></button>)}</div></div><aside className="order-card"><div className="panel-head"><div><p className="caption">CURRENT ORDER</p><h3>Checkout</h3></div><span className="pill">{Object.values(cart).reduce((sum, item) => sum + item.quantity, 0)} items</span></div><label className="customer-field">Customer<input value={customer} onChange={(event) => setCustomer(event.target.value)} /></label>{Object.values(cart).map((item) => <div className="cart-row" key={item.product_id}><span><b>{item.product_name}</b><small>{peso(item.base_price)}</small></span><div><button onClick={() => setCart((current) => { const next = { ...current }; if (item.quantity <= 1) delete next[item.product_id]; else next[item.product_id] = { ...item, quantity: item.quantity - 1 }; return next; })}>−</button>{item.quantity}<button onClick={() => add(item)}>+</button></div></div>)}{!Object.keys(cart).length && <p className="empty">Scan a barcode or select a product.</p>}<div className="total"><span>Subtotal</span><b>{peso(subtotal)}</b></div><div className="total"><span>Tax</span><b>{peso(tax)}</b></div><div className="total grand-total"><span>Total</span><b>{peso(subtotal + tax)}</b></div><button className="save-product full-button" disabled={!Object.keys(cart).length} onClick={checkout}>Complete sale</button>{receipt && <button className="secondary full-button" onClick={() => window.print()}>Print receipt #{receipt.order.order_number}</button>}<div className="recent-orders"><p className="caption">RECENT ORDERS</p>{orders.slice(0, 4).map((order) => <div className="recent-order" key={order.order_id}><span>#{order.order_number}<small>{order.customer_name}</small></span><b>{peso(order.total_amount)}</b></div>)}</div></aside>{receipt && <div className="receipt-print"><h2>Brewline Coffee</h2><p>Order #{receipt.order.order_number}</p><p>{new Date(receipt.order.created_at).toLocaleString()}</p><hr/>{receipt.items.map((item) => <p key={item.product_id}>{item.quantity} × {item.product_name} {peso(item.base_price * item.quantity)}</p>)}<hr/><p>Total: {peso(receipt.order.total_amount)}</p><p>Thank you!</p></div>}</section>;
}
