-- Brew & Co. POS schema. Run in Supabase SQL Editor.
create table if not exists public.products (
  p_id bigint generated by default as identity primary key,
  name text not null,
  sku text not null,
  category text not null default 'Espresso',
  price numeric(10, 2) not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  emoji text not null default '☕'
);

create table if not exists public.sales (
  sales_id text primary key,
  date text not null,
  customer text not null default 'Walk-in customer',
  items integer not null default 0 check (items >= 0),
  total numeric(10, 2) not null default 0 check (total >= 0),
  status text not null default 'completed' check (status in ('completed', 'pending', 'cancelled'))
);

alter table public.products add column if not exists name text;
alter table public.products add column if not exists sku text;
alter table public.products add column if not exists category text default 'Espresso';
alter table public.products add column if not exists price numeric(10, 2) default 0;
alter table public.products add column if not exists stock integer default 0;
alter table public.products add column if not exists emoji text default '☕';

alter table public.sales add column if not exists sales_id text;
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'sales' and column_name = 'id') then
    update public.sales set sales_id = coalesce(sales_id, id::text) where sales_id is null;
  end if;
end $$;
do $$
begin
  if exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'sales' and column_name = 'id') then
    alter table public.sales drop column id;
  end if;
end $$;
alter table public.sales add column if not exists date text;
alter table public.sales add column if not exists customer text default 'Walk-in customer';
alter table public.sales add column if not exists items integer default 0;
alter table public.sales add column if not exists total numeric(10, 2) default 0;
alter table public.sales add column if not exists status text default 'completed';

update public.products set category = 'Espresso' where category is null;
update public.products set price = 0 where price is null;
update public.products set stock = 0 where stock is null;
update public.products set emoji = '☕' where emoji is null;
update public.sales set customer = 'Walk-in customer' where customer is null;
update public.sales set items = 0 where items is null;
update public.sales set total = 0 where total is null;
update public.sales set status = 'completed' where status is null;

alter table public.products alter column name set not null;
alter table public.products alter column sku set not null;
alter table public.products alter column category set not null;
alter table public.products alter column price set not null;
alter table public.products alter column stock set not null;
alter table public.products alter column emoji set not null;
alter table public.sales alter column sales_id set not null;
do $$
declare
  primary_key_name text;
begin
  select constraint_name into primary_key_name
  from information_schema.table_constraints
  where table_schema = 'public' and table_name = 'sales' and constraint_type = 'PRIMARY KEY';
  if primary_key_name is not null then
    execute format('alter table public.sales drop constraint %I', primary_key_name);
  end if;
  alter table public.sales add constraint sales_pkey primary key (sales_id);
end $$;
alter table public.sales alter column date set not null;
alter table public.sales alter column customer set not null;
alter table public.sales alter column items set not null;
alter table public.sales alter column total set not null;
alter table public.sales alter column status set not null;

create unique index if not exists products_sku_key on public.products (sku);
create unique index if not exists sales_sales_id_key on public.sales (sales_id);
create index if not exists sales_date_idx on public.sales (date);

insert into public.products (p_id, name, sku, category, price, stock, emoji)
values
  (1, 'Coconut Cloud Latte', 'BRW-001', 'Espresso', 165, 24, '☕'),
  (2, 'Brown Sugar Oat Latte', 'BRW-002', 'Espresso', 185, 18, '◒'),
  (3, 'Spanish Latte', 'BRW-003', 'Espresso', 175, 32, '◉'),
  (4, 'Strawberry Matcha', 'BRW-004', 'Non-coffee', 195, 16, '✦'),
  (5, 'Dark Cocoa Mocha', 'BRW-005', 'Non-coffee', 185, 12, '●'),
  (6, 'Butter Croissant', 'BRW-006', 'Pastries', 120, 28, '◆'),
  (7, 'Cinnamon Bun', 'BRW-007', 'Pastries', 135, 7, '☀'),
  (8, 'Brewed Coffee', 'BRW-008', 'Espresso', 110, 40, '◌')
on conflict (p_id) do nothing;

insert into public.sales (sales_id, date, customer, items, total, status)
values
  ('#1048', 'Aug 24, 2026 · 10:42 AM', 'Walk-in customer', 3, 86, 'completed'),
  ('#1047', 'Aug 24, 2026 · 09:18 AM', 'Maya Chen', 2, 46, 'completed'),
  ('#1046', 'Aug 23, 2026 · 04:51 PM', 'Walk-in customer', 1, 32, 'completed'),
  ('#1045', 'Aug 23, 2026 · 02:22 PM', 'Jon Bell', 4, 83, 'pending'),
  ('#1044', 'Aug 22, 2026 · 11:07 AM', 'Sofia Reed', 2, 52, 'completed')
on conflict (sales_id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'p_id'),
  coalesce((select max(p_id) from public.products), 1),
  true
);